### ISSUE TITLE
List out python dependencies

### ISSUE THREAD

**Issue by ahmad-reza619** [verssache/igviewstory#1]
I was experimenting with this lib, and i got this error
![Screen Shot 2021-03-14 at 18 18 55](https://user-images.githubusercontent.com/52902060/111066454-beeb2b80-84f1-11eb-903a-3b75d51e378a.png)

so i was thinking that these mean i have to acquire some dependencies, which is not listed on readme, if you could, please list out all dependencies needed. thank you

**Comment by verssache** [comment]
I'm sorry, I've updated it now by adding the requirements.txt file, please type 'pip install -r requirements.txt' then try running again

**Comment by ahmad-reza619** [comment]
Ok thanks, it works perfectly now 👍
